--CRIAR NOVO LOGIN
CREATE LOGIN Aluno
WITH PASSWORD = '1234'

--CRIAR PERFIL DE USUARIO E ATRIBUIR AO ALUNO
CREATE USER Aluno FOR LOGIN Aluno

--DAR PERMISSAO PARA ESTE TIPO DE USUÁRIO FAZER APENAS "SELECT"
GRANT SELECT TO Aluno